import { validate } from './validation.mjs';
import { createCloudSync } from './cloud.js';
'use strict';
const KEY = 'factory-points-v1';
const icons = {customers:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M22 21v-2a4 4 0 0 0-3-3.87"/><circle cx="9" cy="7" r="4"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>',recharge:'<rect x="3" y="5" width="18" height="15" rx="3"/><path d="M3 9h18M12 12v5M9.5 14.5h5M7 2v3"/>',consume:'<path d="M9 3H5v18h14V3h-4M9 2h6v4H9zM8 11h8M8 15h5"/>',ledger:'<path d="M4 3h16v18H4zM8 7h8M8 12h8M8 17h5"/>',packages:'<rect x="3" y="8" width="18" height="4" rx="1"/><path d="M5 12v9h14v-9M12 8v13"/><path d="M12 8C3 8 5 0 9 3l3 5c9 0 7-8 3-5z"/>',categories:'<path d="m8 3-6 4 3 5 3-2v11h8V10l3 2 3-5-6-4c0 4-8 4-8 0z"/>',settings:'<path d="m9 3 1-1h4l1 3 3 1 3 1v4l-2 2-1 3 1 3-3 2-3-1-3 1-3-2-1-3-2-2V9l3-2z"/><circle cx="12" cy="12" r="3"/>',backup:'<path d="M4 16v5h16v-5M12 3v12M7 8l5-5 5 5"/>',plus:'<path d="M12 5v14M5 12h14"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7v1"/>'};
const icon = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name] || icons.info}</svg>`;
const pages = {customers:'客户信息',recharge:'积分充值',consume:'积分消耗',ledger:'积分变动明细',packages:'积分套餐设置',categories:'服装类别',settings:'系统设置',backup:'数据备份'};
const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num = n => Number(n).toLocaleString('zh-CN');
const uid = () => crypto.randomUUID();
const today = () => new Date().toLocaleDateString('sv-SE');
function seed(){const categories=['外套裤子','针织服装','童装','运动服饰','衬衫'];const names=['锦程制衣厂','华盛服饰有限公司','新悦童装工厂','恒丰针织厂','远航运动服饰','XX制衣工厂'];const balances=[12800,8650,5200,3600,7500,2680];const customers=names.map((name,i)=>({id:uid(),name,phone:['13800138000','13912345678','13688889999','13755668899','13566881234','13800138001'][i],category:categories[[0,4,2,1,3,0][i]],machines:[36,24,18,20,32,12][i],points:balances[i],contact:['张先生','李女士','王先生','陈女士','刘先生','赵先生'][i],notes:'',createdAt:new Date().toISOString()}));return {version:1,settings:{title:'藝速科技积分系统',rate:10,lowBalance:1000},categories,customers,packages:[{id:uid(),name:'基础套餐',amount:100,points:1000,bonus:0},{id:uid(),name:'优享套餐',amount:500,points:5000,bonus:500},{id:uid(),name:'尊享套餐',amount:1000,points:10000,bonus:1500}],transactions:customers.map(c=>({id:uid(),customerId:c.id,customerName:c.name,type:'recharge',delta:c.points,balance:c.points,amount:0,note:'演示初始积分',createdAt:c.createdAt})),demo:true};}
let data, storageError='';
try{const saved=localStorage.getItem(KEY);data=saved?JSON.parse(saved):seed();validate(data);const renamed=data.settings.title==='工厂客户积分管理系统';if(renamed)data.settings.title='藝速科技积分系统';if(!saved||renamed)localStorage.setItem(KEY,JSON.stringify(data));}catch(e){data={version:1,settings:{title:'藝速科技积分系统',rate:10,lowBalance:1000},categories:[],customers:[],packages:[],transactions:[],demo:false};storageError='本地数据无法读取，已暂停保存。请先下载原始数据，再从备份恢复。';}
let page='customers', pageNumber=1, filters={}, toastTimer;

function persist(next, restoring=false){try{if(storageError&&!restoring)throw Error('请先恢复有效备份');const current=localStorage.getItem(KEY);if(!restoring&&current!==snapshot)throw Error('数据已在其他窗口变更，请刷新页面后重试');validate(next);const serialized=JSON.stringify(next);localStorage.setItem(KEY,serialized);data=next;snapshot=serialized;storageError='';return true;}catch(e){toast('保存失败：'+e.message);return false;}}
let snapshot;try{snapshot=localStorage.getItem(KEY);}catch{}
function change(fn){const next=structuredClone(data);fn(next);return persist(next);}
function toast(message){const dialog=$('#filter-dialog[open]');if(dialog){let alert=dialog.querySelector('[role="alert"]');if(!alert){alert=document.createElement('p');alert.className='filter-error';alert.setAttribute('role','alert');dialog.querySelector('form').prepend(alert);}alert.textContent=message;}$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function heading(title,sub,action=''){return `<div class="page-heading"><div><div class="eyebrow">CUSTOMER POINTS MANAGEMENT</div><h1>${title}</h1><p class="subtitle">${sub}</p></div>${action||`<span class="date-label">${new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'})}</span>`}</div>`;}
function button(label,action,cls='primary',symbol=''){return `<button type="button" class="button ${cls}" data-action="${action}">${symbol?icon(symbol):''}${label}</button>`;}
function options(values,selected,all=''){return (all?`<option value="">${all}</option>`:'')+values.map(v=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(v)}</option>`).join('');}
function field(label,name,value='',type='text',extra=''){return `<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}></div>`;}
function selectField(label,name,opts){return `<div class="field"><label for="${name}">${label}</label><select id="${name}" name="${name}">${opts}</select></div>`;}
function stats(){const items=[['客户总数',data.customers.length,'家','已建立档案的合作客户','customers'],['现有积分',data.customers.reduce((n,c)=>n+c.points,0),'分','所有客户当前可用积分','recharge'],['累计消耗',data.transactions.filter(t=>t.type==='consume').reduce((n,t)=>n-t.delta,0),'分','已记录的积分消耗总额','consume'],['机器总数',data.customers.reduce((n,c)=>n+c.machines,0),'台','客户登记的设备总数','settings']];return `<div class="stats">${items.map(([label,value,unit,foot,i])=>`<div class="stat"><div class="stat-label">${label}</div><div class="stat-icon">${icon(i)}</div><div class="stat-value">${num(value)}<small>${unit}</small></div><div class="stat-foot">${foot}</div></div>`).join('')}</div>`;}
function table(headers,rows,empty='暂无数据'){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}" class="empty">${empty}</td></tr>`}</tbody></table></div>`;}
function note(){return `<div class="note">${icon('info')}数据保存在当前浏览器，请定期导出本地备份。</div>`;}
function render(){closeFilters();page=location.hash.slice(1)||'customers';if(!pages[page])page='customers';$('#brand-title').textContent=data.settings.title;document.title=data.settings.title;$('#nav').innerHTML=Object.entries(pages).map(([id,title])=>`<a href="#${id}" class="nav-item ${id===page?'active':''}" ${id===page?'aria-current="page"':''}><span class="nav-icon">${icon(id)}</span>${title}</a>`).join('');$('#main').innerHTML=(storageError?`<div class="error-banner">${storageError}</div>`:'')+({customers:customersPage,recharge:transactionPage,consume:transactionPage,ledger:ledgerPage,packages:packagesPage,categories:categoriesPage,settings:settingsPage,backup:backupPage}[page])()+note();document.body.dataset.page=page;document.querySelectorAll('.table-wrap table').forEach(table=>{const headers=[...table.querySelectorAll('th')].map(h=>h.textContent);table.querySelectorAll('tbody tr').forEach(row=>[...row.cells].forEach((cell,i)=>cell.dataset.label=headers[i]));});setupFilters();if(page==='recharge'||page==='consume')updatePreview();}
function filteredCustomers(){return data.customers.filter(c=>(!filters.name||c.name.toLowerCase().includes(filters.name.toLowerCase()))&&(!filters.phone||c.phone.includes(filters.phone))&&(!filters.category||c.category===filters.category));}
function customersPage(){const list=filteredCustomers();const max=Math.max(1,Math.ceil(list.length/8));pageNumber=Math.min(pageNumber,max);return heading('客户信息','管理工厂客户档案，随时掌握积分与设备情况')+stats()+`<form id="filter-form" class="panel filters">${field('工厂名称','name',filters.name||'','search','placeholder="搜索工厂名称"')}${field('联系电话','phone',filters.phone||'','search','placeholder="输入联系电话"')}${selectField('服装类别','category',options(data.categories,filters.category,'全部类别'))}<div class="filter-actions"><button class="button primary" type="submit">${icon('search')}查询</button>${button('重置','reset','secondary')}${button('新增客户','add-customer','primary','plus')}</div></form><section class="panel"><div class="panel-header"><h2>客户列表<span class="count">${list.length} 位客户</span></h2>${button('导出客户','export-customers','secondary','backup')}</div>${table(['序号','工厂名称','联系方式','服装类别','现有积分','机器数','操作'],list.slice((pageNumber-1)*8,pageNumber*8).map((c,i)=>`<tr><td>${String((pageNumber-1)*8+i+1).padStart(2,'0')}</td><td><div class="customer-cell"><span class="factory-avatar">${esc(c.name.slice(0,1))}</span><div><div class="customer-name">${esc(c.name)}</div><div class="cell-sub">${esc(c.contact||'未填写联系人')}</div></div></div></td><td>${esc(c.phone)}</td><td><span class="tag">${esc(c.category)}</span></td><td><span class="points ${c.points<data.settings.lowBalance?'negative':''}">${num(c.points)}</span></td><td>${c.machines}<span class="cell-sub"> 台</span></td><td><div class="row-actions"><button class="text-button" data-action="recharge-customer" data-id="${esc(c.id)}">充值</button><button class="text-button orange" data-action="consume-customer" data-id="${esc(c.id)}">消耗</button><button class="text-button muted" data-action="detail-customer" data-id="${esc(c.id)}">明细</button><button class="text-button muted" data-action="edit-customer" data-id="${esc(c.id)}">编辑</button></div></td></tr>`),'没有符合条件的客户，请调整筛选条件或新增客户')}<div class="table-footer"><span>共 ${list.length} 条记录 · 每页 8 条</span><div class="pagination"><button data-action="prev" ${pageNumber===1?'disabled':''} aria-label="上一页">‹</button><button class="current">${pageNumber}</button><span>/ ${max}</span><button data-action="next" ${pageNumber===max?'disabled':''} aria-label="下一页">›</button></div></div></section>`;}
let selectedCustomer='', selectedPackage='';
function transactionPage(){const recharge=page==='recharge';return heading(pages[page],recharge?'为客户充值积分，支持套餐充值与自定义充值':'记录客户积分使用情况，自动扣减余额并生成流水')+`<div class="grid-two"><section class="panel"><div class="panel-header"><h2>${recharge?'充值':'消耗'}登记</h2><span class="tag">${recharge?'积分入账':'积分出账'}</span></div><form id="transaction-form" class="content-pad form-stack">${selectField('选择客户','customerId','<option value="">请选择工厂客户</option>'+data.customers.map(c=>`<option value="${esc(c.id)}" ${c.id===selectedCustomer?'selected':''}>${esc(c.name)} · ${esc(c.phone)}</option>`).join(''))}${recharge?`<div class="field"><label>选择充值套餐</label><div class="package-options"><button type="button" class="package-option selected" data-action="choose-package" data-id="">自定义</button>${data.packages.map(p=>`<button type="button" class="package-option" data-action="choose-package" data-id="${esc(p.id)}">${esc(p.name)} · ¥${num(p.amount)}</button>`).join('')}</div></div><div class="form-grid">${field('充值金额（元）','amount','','number','required min="0.01" max="100000000" step="0.01" placeholder="输入充值金额"')}${field('到账积分（含赠送）','points','','number','required min="1" max="1000000000" step="1" placeholder="根据兑换比例计算，可修改"')}</div>`:field('消耗积分','points','','number','required min="1" max="1000000000" step="1" placeholder="输入本次消耗的积分"')}<div class="field"><label for="note">${recharge?'充值备注':'消耗用途'}</label><textarea id="note" name="note" maxlength="200" ${recharge?'':'required'} placeholder="${recharge?'可填写付款方式、经办说明等':'请填写消耗用途，例如：设备维护、服务兑换'}"></textarea></div><p class="help">${recharge?`默认兑换比例：1 元 = ${num(data.settings.rate)} 积分。金额仅用于记账，不涉及在线支付。`:'积分不足时无法提交；已入账流水保留，不支持直接删除。'}</p><button type="submit" class="button primary">确认${recharge?'充值':'消耗'}</button></form></section><section class="panel"><div class="panel-header"><h2>客户积分概览</h2></div><div class="content-pad" id="balance-preview"></div></section></div>`;}
function updatePreview(){const c=data.customers.find(c=>c.id===$('#customerId').value);const p=Number($('#points').value)||0;$('#balance-preview').innerHTML=c?`<div class="balance-preview">${esc(c.name)} · 当前可用积分<strong>${num(c.points)} <small>分</small></strong></div><div class="summary-list"><div class="summary-line"><span>联系人</span><strong>${esc(c.contact||'—')}</strong></div><div class="summary-line"><span>联系电话</span><strong>${esc(c.phone)}</strong></div><div class="summary-line"><span>本次${page==='recharge'?'增加':'消耗'}</span><strong>${num(p)} 分</strong></div><div class="summary-line"><span>预计剩余积分</span><strong class="points">${num(c.points+(page==='recharge'?p:-p))} 分</strong></div></div>`:'<div class="empty">选择客户后查看积分余额与本次变动</div>';}
function ledgerRows(){return data.transactions.filter(t=>{const date=new Date(t.createdAt).toLocaleDateString('sv-SE');return (!filters.customer||t.customerId===filters.customer)&&(!filters.type||t.type===filters.type)&&(!filters.start||date>=filters.start)&&(!filters.end||date<=filters.end);}).slice().reverse();}
function ledgerPage(){const rows=ledgerRows();return heading('积分变动明细','每一笔积分变动都有迹可循，清晰记录充值与消耗')+`<form id="ledger-filter" class="panel filters">${selectField('工厂客户','customer','<option value="">全部客户</option>'+data.customers.map(c=>`<option value="${esc(c.id)}" ${filters.customer===c.id?'selected':''}>${esc(c.name)}</option>`).join(''))}${selectField('变动类型','type',`<option value="">全部类型</option><option value="recharge" ${filters.type==='recharge'?'selected':''}>积分充值</option><option value="consume" ${filters.type==='consume'?'selected':''}>积分消耗</option>`)}${field('开始日期','start',filters.start||'','date')}${field('结束日期','end',filters.end||'','date')}<div class="filter-actions"><button class="button primary">查询</button>${button('重置','reset','secondary')}</div></form><section class="panel"><div class="panel-header"><h2>积分流水<span class="count">${rows.length} 条</span></h2>${button('导出流水','export-ledger','secondary','backup')}</div>${table(['时间','工厂名称','类型','变动积分','变动后余额','金额（元）','备注'],rows.map(t=>`<tr><td>${esc(new Date(t.createdAt).toLocaleString('zh-CN',{hour12:false}))}</td><td class="customer-name">${esc(t.customerName)}</td><td><span class="tag">${t.type==='recharge'?'充值':'消耗'}</span></td><td class="${t.delta>0?'positive':'negative'}">${t.delta>0?'+':''}${num(t.delta)}</td><td>${num(t.balance)}</td><td>${t.amount?num(t.amount):'—'}</td><td>${esc(t.note||'—')}</td></tr>`),'暂无积分变动记录')}</section>`;}
function packagesPage(){return heading('积分套餐设置','设置常用充值档位与赠送积分，让充值操作更高效',button('新增套餐','add-package','primary','plus'))+`<div class="card-grid">${data.packages.map(p=>`<article class="package-card"><span class="tag">充值套餐</span><h2 style="margin-top:18px">${esc(p.name)}</h2><div class="package-price">¥ ${num(p.amount)}</div><p>基础积分 <strong>${num(p.points)}</strong> 分</p><p>额外赠送 <strong class="positive">${num(p.bonus)}</strong> 分</p><p>合计到账 <strong>${num(p.points+p.bonus)}</strong> 分</p><div class="row-actions"><button class="text-button" data-action="edit-package" data-id="${esc(p.id)}">编辑套餐</button><button class="text-button red" data-action="delete-package" data-id="${esc(p.id)}">删除</button></div></article>`).join('')||'<div class="empty">暂无套餐，点击新增套餐开始设置</div>'}</div>`;}
function categoriesPage(){return heading('服装类别','维护客户服装类别，便于分类管理与快速筛选',button('新增类别','add-category','primary','plus'))+`<section class="panel"><div class="panel-header"><h2>类别列表<span class="count">${data.categories.length} 个类别</span></h2></div>${table(['序号','类别名称','关联客户','操作'],data.categories.map((c,i)=>`<tr><td>${i+1}</td><td class="customer-name">${esc(c)}</td><td>${data.customers.filter(x=>x.category===c).length} 家</td><td><div class="row-actions"><button class="text-button" data-action="edit-category" data-index="${i}">编辑</button><button class="text-button red" data-action="delete-category" data-index="${i}">删除</button></div></td></tr>`))}</section>`;}
function settingsPage(){return heading('系统设置','配置系统名称与默认积分规则')+`<section class="panel"><div class="panel-header"><h2>基础设置</h2></div><form id="settings-form" class="content-pad form-stack" style="max-width:650px">${field('系统名称','title',data.settings.title,'text','required maxlength="40"')}${field('默认兑换比例（每 1 元获得的积分）','rate',data.settings.rate,'number','required min="1" max="100000" step="1"')}${field('低余额提醒阈值（积分）','lowBalance',data.settings.lowBalance,'number','required min="0" max="1000000000" step="1"')}<p class="help">低于提醒阈值的客户余额将显示为橙色。兑换比例仅用于后续自定义充值，不影响已有积分与充值套餐。</p><div><button class="button primary" type="submit">保存设置</button></div></form></section><section class="panel"><div class="panel-header"><h2>运行环境</h2><span class="tag">本地数据模式</span></div><div class="content-pad"><p class="help">日常操作保存在当前浏览器，可在数据备份中导出和恢复 JSON 文件。顶部「管理员」为演示身份。</p></div></section>`;}
function backupPage(){return heading('数据备份','导出本地备份，或从备份文件恢复数据')+`<div class="grid-two"><section class="panel content-pad"><div class="backup-icon">↗</div><h2>导出数据备份</h2><p class="subtitle">将客户、积分流水、套餐与设置保存为 JSON 文件。</p><div class="summary-list"><div class="summary-line"><span>客户档案</span><strong>${data.customers.length} 条</strong></div><div class="summary-line"><span>积分流水</span><strong>${data.transactions.length} 条</strong></div></div><div class="backup-actions">${button('下载完整备份','export-backup','primary','backup')}${storageError?button('下载原始数据','export-raw','secondary'):''}</div></section><section class="panel content-pad"><div class="backup-icon">↙</div><h2>恢复数据备份</h2><p class="subtitle">从本系统导出的 JSON 文件恢复。恢复将覆盖当前浏览器中的数据。</p><label class="field" style="margin-top:25px" for="import-file">选择备份文件<input class="file-input" id="import-file" type="file" accept=".json,application/json"></label><p class="help" style="margin-top:15px">导入前会校验数据并显示摘要，确认后才会替换现有数据。</p></section></div>${data.demo?`<section class="panel"><div class="panel-header"><h2>演示数据</h2><span class="tag">首次使用</span></div><div class="content-pad"><p class="help">当前包含示例客户和初始积分。正式使用前，可清空客户与流水，保留套餐、类别和系统设置。</p><div class="backup-actions">${button('清空客户与流水','clear-demo','danger')}</div></div></section>`:''}`;}
let modalSubmit=null;
const DEFAULT_CLEAR_PASSWORD = '88888888';
function clearDataModal() {
  openModal('清空客户与积分流水', `
    <p class="help">将删除当前全部 ${data.customers.length} 个客户与 ${data.transactions.length} 条流水，包括你新增的记录。请先导出备份。</p>
    <div class="field" style="margin-top:20px">
      <label for="clear-password">清空密码</label>
      <input id="clear-password" name="clearPassword" type="password" required autocomplete="off" placeholder="请输入清空密码" aria-describedby="clear-password-error">
      <p id="clear-password-error" role="alert" style="color:#ec8792;margin:0;font-size:12px"></p>
    </div>`, form => {
      if (form.clearPassword !== DEFAULT_CLEAR_PASSWORD) {
        $('#clear-password-error').textContent = '密码错误，未清空任何数据，请重新输入。';
        $('#clear-password').setAttribute('aria-invalid', 'true');
        $('#clear-password').value = '';
        $('#clear-password').focus();
        return;
      }
      if (change(next => { next.customers = []; next.transactions = []; next.demo = false; })) {
        $('#modal').close();
        render();
        toast('客户与积分流水已清空');
      }
    }, '确认清空');
  $('#clear-password').focus();
}
function openModal(title,body,onSubmit,label='保存'){ $('#modal-title').textContent=title;$('#modal-body').innerHTML=body;$('#save-modal').textContent=label;modalSubmit=onSubmit;$('#save-modal').disabled=false;$('#modal').showModal();}
function confirmAction(title,text,fn,label='确认'){openModal(title,`<p class="help">${esc(text)}</p>`,async()=>{const save=$('#save-modal');if(save.disabled)return;save.disabled=true;try{if(await fn()!==false){$('#modal').close();render();}}catch(error){toast(error.message);}finally{save.disabled=false;}},label);}
function customerModal(id){const c=data.customers.find(x=>x.id===id)||{name:'',phone:'',category:data.categories[0],machines:0,contact:'',notes:''};if(!data.categories.length){toast('请先在服装类别中新增类别');return;}openModal(id?'编辑客户':'新增客户',`<div class="form-grid">${field('工厂名称 *','factoryName',c.name,'text','required maxlength="60"')}${field('联系人','contact',c.contact,'text','maxlength="30"')}${field('联系电话 *','customerPhone',c.phone,'tel','required pattern="[0-9+() -]{6,20}" maxlength="20" title="请输入 6 至 20 位联系电话"')}${selectField('服装类别 *','customerCategory',options(data.categories,c.category))}${field('机器数量 *','machines',c.machines,'number','required min="0" max="1000000" step="1"')}<div class="field full"><label for="notes">备注</label><textarea id="notes" name="notes" maxlength="300">${esc(c.notes||'')}</textarea></div></div>`,f=>{const name=f.factoryName.trim(),phone=f.customerPhone.trim();if(!name)return toast('请输入工厂名称');if(data.customers.some(x=>x.id!==id&&x.name===name))return toast('该工厂名称已存在');if(change(d=>{const values={name,phone,category:f.customerCategory,machines:Number(f.machines),contact:f.contact.trim(),notes:f.notes.trim()};if(id)Object.assign(d.customers.find(x=>x.id===id),values);else d.customers.push({...values,id:uid(),points:0,createdAt:new Date().toISOString()});})){ $('#modal').close();render();toast('客户档案已保存');}});}
function packageModal(id){const p=data.packages.find(x=>x.id===id)||{name:'',amount:100,points:1000,bonus:0};openModal(id?'编辑积分套餐':'新增积分套餐',`<div class="form-grid">${field('套餐名称','packageName',p.name,'text','required maxlength="30"')}${field('充值金额（元）','packageAmount',p.amount,'number','required min="0.01" max="100000000" step="0.01"')}${field('基础积分','packagePoints',p.points,'number','required min="1" max="1000000000" step="1"')}${field('赠送积分','bonus',p.bonus,'number','required min="0" max="1000000000" step="1"')}</div>`,f=>{if(!f.packageName.trim())return toast('请输入套餐名称');if(change(d=>{const v={name:f.packageName.trim(),amount:Number(f.packageAmount),points:Number(f.packagePoints),bonus:Number(f.bonus)};if(id)Object.assign(d.packages.find(x=>x.id===id),v);else d.packages.push({...v,id:uid()});})){ $('#modal').close();render();toast('套餐已保存');}});}
function categoryModal(index){const old=data.categories[index];openModal(old?'编辑服装类别':'新增服装类别',field('类别名称','categoryName',old||'','text','required maxlength="30"'),f=>{const name=f.categoryName.trim();if(!name)return toast('请输入类别名称');if(data.categories.includes(name)&&name!==old)return toast('该类别已存在');if(change(d=>{if(old){d.categories[index]=name;d.customers.forEach(c=>{if(c.category===old)c.category=name;});}else d.categories.push(name);})){ $('#modal').close();render();toast('类别已保存');}});}
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csv(rows,name){download('\uFEFF'+rows.map(r=>r.map(v=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}).join(',')).join('\r\n'),name+'-'+today()+'.csv','text/csv;charset=utf-8');}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.closest('form')&&b.type==='submit'&&b.dataset.action)e.preventDefault();const id=b.dataset.id,idx=Number(b.dataset.index);switch(b.dataset.action){case'add-customer':customerModal();break;case'edit-customer':customerModal(id);break;case'reset':filters={};pageNumber=1;render();break;case'prev':pageNumber--;render();break;case'next':pageNumber++;render();break;case'recharge-customer':case'consume-customer':selectedCustomer=id;selectedPackage='';location.hash=b.dataset.action==='recharge-customer'?'recharge':'consume';break;case'detail-customer':filters={customer:id};location.hash='ledger';break;case'add-package':packageModal();break;case'edit-package':packageModal(id);break;case'delete-package':confirmAction('删除积分套餐','删除后无法再选择此套餐，历史充值记录会保留。',()=>change(d=>d.packages=d.packages.filter(x=>x.id!==id)),'删除');break;case'add-category':categoryModal();break;case'edit-category':categoryModal(idx);break;case'delete-category':if(data.customers.some(c=>c.category===data.categories[idx]))return toast('此类别仍有关联客户，请先修改客户类别');confirmAction('删除服装类别',`确认删除「${data.categories[idx]}」？`,()=>change(d=>d.categories.splice(idx,1)),'删除');break;case'choose-package':{selectedPackage=id;const p=data.packages.find(x=>x.id===id);$('#amount').value=p?p.amount:'';$('#points').value=p?p.points+p.bonus:'';$('#amount').readOnly=!!p;$('#points').readOnly=!!p;document.querySelectorAll('.package-option').forEach(x=>x.classList.toggle('selected',x.dataset.id===id));updatePreview();break;}case'export-customers':csv([['工厂名称','联系人','联系电话','服装类别','现有积分','机器数','备注'],...filteredCustomers().map(c=>[c.name,c.contact,c.phone,c.category,c.points,c.machines,c.notes])],'客户列表');break;case'export-ledger':csv([['时间','工厂名称','类型','变动积分','余额','金额','备注'],...ledgerRows().map(t=>[new Date(t.createdAt).toLocaleString('zh-CN'),t.customerName,t.type==='recharge'?'充值':'消耗',t.delta,t.balance,t.amount,t.note])],'积分流水');break;case'export-backup':download(JSON.stringify(data,null,2),'积分系统备份-'+today()+'.json','application/json');toast('备份已生成');break;case'export-raw':try{download(localStorage.getItem(KEY)||'','积分系统原始数据.txt','text/plain');}catch{toast('浏览器不允许访问本地存储');}break;case'clear-demo':clearDataModal();break;}});
document.addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));switch(e.target.id){case'modal-form':modalSubmit?.(f);break;case'filter-form':filters=f;pageNumber=1;render();break;case'ledger-filter':if(f.start&&f.end&&f.start>f.end)return toast('开始日期不能晚于结束日期');filters=f;render();break;case'settings-form':if(!f.title.trim())return toast('请输入系统名称');if(change(d=>d.settings={title:f.title.trim(),rate:Number(f.rate),lowBalance:Number(f.lowBalance)})){render();toast('系统设置已保存');}break;case'transaction-form':{const c=data.customers.find(x=>x.id===f.customerId);const points=Number(f.points),amount=page==='recharge'?Number(f.amount):0;const recharge=page==='recharge';if(!c)return toast('请选择客户');if(!Number.isSafeInteger(points)||points<=0)return toast('积分必须为正整数');if(recharge&&(!Number.isFinite(amount)||amount<=0))return toast('请输入有效充值金额');if(!recharge&&points>c.points)return toast('客户积分不足，无法完成消耗');if(!recharge&&!f.note.trim())return toast('请填写消耗用途');confirmAction(recharge?'确认积分充值':'确认积分消耗',`${c.name}：${recharge?'增加':'扣减'} ${num(points)} 积分${recharge?'，记账金额 ¥'+num(amount):''}，操作后余额 ${num(c.points+(recharge?points:-points))} 积分。`,()=>{const ok=change(d=>{const customer=d.customers.find(x=>x.id===c.id);customer.points+=recharge?points:-points;d.transactions.push({id:uid(),customerId:c.id,customerName:c.name,type:recharge?'recharge':'consume',delta:recharge?points:-points,balance:customer.points,amount,note:f.note.trim()||(selectedPackage?data.packages.find(x=>x.id===selectedPackage)?.name:'自定义充值'),createdAt:new Date().toISOString()});});if(ok){selectedCustomer=c.id;selectedPackage='';toast(recharge?'充值成功，积分已到账':'消耗成功，流水已记录');}return ok;},recharge?'确认充值':'确认消耗');break;}}});
document.addEventListener('input',e=>{if(e.target.closest('#transaction-form')){if(e.target.id==='amount'&&!selectedPackage)$('#points').value=Math.floor(Number(e.target.value)*data.settings.rate)||'';updatePreview();}});
document.addEventListener('change',async e=>{if(e.target.id==='customerId')updatePreview();if(e.target.id==='import-file'){const file=e.target.files[0];if(!file)return;if(file.size>20*1024*1024){toast('备份文件不能超过 20 MB');e.target.value='';return;}try{const imported=JSON.parse(await file.text());validate(imported);confirmAction('确认恢复备份',`文件包含 ${imported.customers.length} 个客户、${imported.transactions.length} 条流水及 ${imported.packages.length} 个套餐。恢复将覆盖当前全部数据，请确认已保存当前备份。`,()=>{if(persist(imported,true)){selectedCustomer='';selectedPackage='';filters={};toast('备份恢复成功');return true;}return false;},'覆盖并恢复');}catch(error){toast('备份无效：'+error.message);}e.target.value='';}});
$('#close-modal').onclick=$('#cancel-modal').onclick=()=>$('#modal').close();
window.addEventListener('hashchange',()=>{if(location.hash!=='#ledger'||!filters.customer)filters={};pageNumber=1;selectedPackage='';render();window.scrollTo(0,0);});
window.addEventListener('storage',e=>{if(e.key===KEY)toast('其他窗口已更新数据，请刷新页面以读取最新记录');});
const cloud=createCloudSync({getData:()=>data,validate,esc,toast,render,confirmAction,download,restore:next=>{const ok=persist(next,true);if(ok){selectedCustomer='';selectedPackage='';filters={};}return ok;},getSnapshot:()=>snapshot});
const mobileQuery = matchMedia('(max-width:760px)');
let filterSource = null;
const filterDialog = document.createElement('dialog');
filterDialog.id = 'filter-dialog';
filterDialog.setAttribute('aria-labelledby', 'filter-title');
document.body.append(filterDialog);
function closeFilters() {
  if (!filterSource) return;
  const form = filterDialog.querySelector('form');
  if (form) filterSource.replaceWith(form);
  filterSource = null;
  filterDialog.close();
  filterDialog.replaceChildren();
}
function setupFilters() {
  const form = $('#filter-form, #ledger-filter');
  if (!form) return;
  const count = Object.values(filters).filter(Boolean).length;
  const bar = document.createElement('div');
  bar.className = 'mobile-filter-bar';
  bar.innerHTML = `<button type="button" class="button secondary" aria-haspopup="dialog">${icon('search')}查询${count ? ` (${count})` : ''}</button>${page === 'customers' ? button('新增客户','add-customer','primary','plus') : ''}`;
  form.before(bar);
  bar.firstElementChild.onclick = () => {
    filterSource = document.createComment('filters');
    form.replaceWith(filterSource);
    filterDialog.innerHTML = '<div class="modal-header"><h2 id="filter-title">查询条件</h2><button type="button" class="icon-button" aria-label="关闭查询">×</button></div>';
    filterDialog.append(form);
    filterDialog.querySelector('.icon-button').onclick = closeFilters;
    filterDialog.showModal();
  };
}
filterDialog.addEventListener('cancel', event => { event.preventDefault(); closeFilters(); });
mobileQuery.addEventListener('change', closeFilters);
const themeControl = document.createElement('select');
themeControl.className = 'theme-control';
themeControl.setAttribute('aria-label', '界面主题');
themeControl.innerHTML = '<option value="light">蓝白</option><option value="dark">蓝黑</option>';
let theme = 'light';
try { theme = localStorage.getItem('factory-points-theme') === 'dark' ? 'dark' : 'light'; } catch {}
function applyTheme(value) { document.documentElement.dataset.theme = value; themeControl.value = value; }
applyTheme(theme);
$('.topbar-right').prepend(themeControl);
themeControl.onchange = () => {
  applyTheme(themeControl.value);
  try { localStorage.setItem('factory-points-theme', themeControl.value); } catch { toast('主题已切换，但浏览器未允许保存偏好'); }
};
render();
