export function validate(d){
  if(!d||d.version!==1||!d.settings||typeof d.settings.title!=='string'||!d.settings.title.trim()||d.settings.title.length>40||!Number.isFinite(d.settings.rate)||d.settings.rate<=0||!Number.isSafeInteger(d.settings.lowBalance)||d.settings.lowBalance<0)throw Error('系统设置格式错误');
  for(const k of ['customers','categories','packages','transactions'])if(!Array.isArray(d[k]))throw Error('数据结构不完整');
  if(d.categories.some(c=>typeof c!=='string'||!c.trim())||new Set(d.categories).size!==d.categories.length)throw Error('类别数据错误');
  for(const k of ['customers','packages','transactions'])if(new Set(d[k].map(x=>x.id)).size!==d[k].length||d[k].some(x=>typeof x.id!=='string'||!x.id))throw Error('存在无效或重复编号');
  for(const c of d.customers){const categories=Array.isArray(c.category)?c.category:[c.category];if(typeof c.name!=='string'||!c.name.trim()||typeof c.phone!=='string'||!categories.length||categories.some(x=>!d.categories.includes(x))||new Set(categories).size!==categories.length||!Number.isSafeInteger(c.points)||c.points<0||!Number.isSafeInteger(c.machines)||c.machines<0)throw Error('客户数据错误');}
  for(const p of d.packages)if(typeof p.name!=='string'||!p.name.trim()||!Number.isFinite(p.amount)||p.amount<=0||!Number.isSafeInteger(p.points)||p.points<=0||!Number.isSafeInteger(p.bonus)||p.bonus<0||!Number.isSafeInteger(p.points+p.bonus))throw Error('套餐数据错误');
  for(const t of d.transactions)if(!d.customers.some(c=>c.id===t.customerId)||typeof t.customerName!=='string'||!['recharge','consume'].includes(t.type)||!Number.isSafeInteger(t.delta)||t.delta===0||!Number.isSafeInteger(t.balance)||t.balance<0||!Number.isFinite(t.amount)||t.amount<0||typeof t.note!=='string'||!Number.isFinite(Date.parse(t.createdAt)))throw Error('积分流水数据错误');
  if(d.machinePurchases!==undefined&&!Array.isArray(d.machinePurchases))throw Error('采买机器数据错误');
  const machineIds=new Set();
  for(const p of d.machinePurchases||[]){const amount=p.amount??0,bonusRate=p.bonusRate??0,bonusPoints=p.bonusPoints??0;if(typeof p.id!=='string'||!p.id||machineIds.has(p.id)||!d.customers.some(c=>c.id===p.customerId)||typeof p.customerName!=='string'||!Number.isSafeInteger(p.quantity)||p.quantity<=0||!Number.isFinite(amount)||amount<0||!Number.isSafeInteger(bonusRate)||bonusRate<0||!Number.isSafeInteger(bonusPoints)||bonusPoints<0||!Number.isSafeInteger(Math.floor(amount*bonusRate))||bonusPoints!==Math.floor(amount*bonusRate)||typeof p.note!=='string'||!Number.isFinite(Date.parse(p.createdAt)))throw Error('采买机器数据错误');machineIds.add(p.id);}
  const balances=new Map();for(const t of d.transactions){const balance=(balances.get(t.customerId)||0)+t.delta;if(balance!==t.balance)throw Error('流水余额不一致');balances.set(t.customerId,balance);}for(const c of d.customers)if((balances.get(c.id)||0)!==c.points)throw Error('客户余额与流水不一致');
}
