const { test, expect } = require('@playwright/test');
const key = 'factory-points-v1';
test('客户建档、充值、消耗、余额校验与刷新持久化', async ({ page }) => {
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await page.getByRole('button',{name:'新增客户'}).click();
  await page.getByLabel('工厂名称 *').fill('测试服装厂');
  await page.getByLabel('联系电话 *').fill('13812345678');
  await page.getByLabel('机器数量 *').fill('8');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  const row=page.getByRole('row').filter({hasText:'测试服装厂'});
  await expect(row).toBeVisible();
  await row.getByRole('button',{name:'充值',exact:true}).click();
  await page.getByRole('button',{name:'优享套餐 · ¥500'}).click();
  await expect(page.getByLabel('到账积分（含赠送）')).toHaveValue('5500');
  await page.getByRole('button',{name:'确认充值',exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:'确认充值',exact:true}).click();
  await page.getByRole('link',{name:'积分消耗',exact:true}).click();
  await page.getByLabel('消耗积分',{exact:true}).fill('6000');
  await page.getByLabel('消耗用途').fill('设备维护');
  await page.getByRole('button',{name:'确认消耗',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('积分不足');
  await page.getByLabel('消耗积分',{exact:true}).fill('500');
  await page.getByRole('button',{name:'确认消耗',exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:'确认消耗',exact:true}).click();
  await page.reload();
  const saved=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);
  const c=saved.customers.find(c=>c.name==='测试服装厂');
  expect(c.points).toBe(5000);
  expect(saved.transactions.filter(t=>t.customerId===c.id).map(t=>t.delta)).toEqual([5500,-500]);
  await page.getByRole('link',{name:'积分变动明细',exact:true}).click();
  await expect(page.getByRole('row').filter({hasText:'设备维护'})).toBeVisible();
  expect(errors).toEqual([]);
});
test('备份校验、导出与恢复', async ({ page }) => {
  await page.goto('/#backup');
  const original=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'下载完整备份'}).click();
  expect((await downloadPromise).suggestedFilename()).toMatch(/\.json$/);
  const invalid=structuredClone(original);invalid.customers[0].points++;
  await page.locator('#import-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});
  await expect(page.locator('#toast')).toContainText('余额与流水不一致');
  await page.getByRole('button',{name:'清空客户与流水',exact:true}).click();
  const password=page.getByLabel('清空密码',{exact:true});
  await expect(password).toHaveAttribute('type','password');
  await page.getByRole('button',{name:'确认清空',exact:true}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key)).toEqual(original);
  await password.fill('wrong-password');
  await page.getByRole('button',{name:'确认清空',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('密码错误');
  expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key)).toEqual(original);
  await page.getByRole('button',{name:'取消',exact:true}).click();
  await page.getByRole('button',{name:'清空客户与流水',exact:true}).click();
  await expect(password).toHaveValue('');
  await password.fill('88888888');
  await page.getByRole('button',{name:'确认清空',exact:true}).click();
  expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).customers.length,key)).toBe(0);
  const cleared=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);
  expect(cleared.transactions).toEqual([]);
  expect(cleared.settings).toEqual(original.settings);
  expect(cleared.packages).toEqual(original.packages);
  expect(cleared.categories).toEqual(original.categories);
  await page.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(original))});
  await page.getByRole('button',{name:'覆盖并恢复'}).click();
  expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).customers.length,key)).toBe(6);
});
test('类别关联更新、使用中删除保护与手机布局', async ({ page }) => {
  await page.goto('/#categories');
  await page.getByRole('row').filter({hasText:'外套裤子'}).getByRole('button',{name:'编辑'}).click();
  await page.getByLabel('类别名称').fill('外套与裤装');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  const row=page.getByRole('row').filter({hasText:'外套与裤装'});
  await expect(row).toContainText('2 家');
  await row.getByRole('button',{name:'删除'}).click();
  await expect(page.getByRole('status')).toContainText('仍有关联客户');
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('link',{name:'客户信息',exact:true}).click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await expect(page.getByRole('status')).not.toHaveClass('visible');
  await page.screenshot({path:'test-results/mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:960});
  await page.screenshot({path:'test-results/desktop.png',fullPage:true});
});
test('旧窗口不能覆盖另一个窗口更新的数据', async ({ page, context }) => {
  await page.goto('/#settings');
  const other=await context.newPage();
  await other.goto('/#settings');
  await other.getByLabel('系统名称',{exact:true}).fill('新的系统名称');
  await other.getByRole('button',{name:'保存设置'}).click();
  await page.getByLabel('系统名称',{exact:true}).fill('旧窗口覆盖');
  await page.getByRole('button',{name:'保存设置'}).click();
  await expect(page.getByRole('status')).toContainText('其他窗口变更');
  expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).settings.title,key)).toBe('新的系统名称');
});
